package com.poopers.proyectocriptografia.pantallas;

import com.poopers.proyectocriptografia.comunicacion.AutoridadCertificadora;
import com.poopers.proyectocriptografia.comunicacion.Cliente;
import com.poopers.proyectocriptografia.comunicacion.DetectorIP;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 * Este frame es usado por los emisores de archivos que le enviarán archivos al
 * receptor.
 */
public class EmisorArchivoForm extends JFrame {

    /**
     * Creates new form EmisorArchivoForm
     */
    public EmisorArchivoForm() {
        initComponents();
        configure();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTituloEmisor = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jtfIPCliente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtfNombreUsuario = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtfIpAutoridad = new javax.swing.JTextField();
        btnSolicitarClave = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jtfClavePublica = new javax.swing.JTextField();
        jtfClavePrivada = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        btnElegirArchivo = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jtfIPServidor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(900, 500));
        setMinimumSize(new java.awt.Dimension(900, 500));
        setPreferredSize(new java.awt.Dimension(900, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(900, 500));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblTituloEmisor.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        lblTituloEmisor.setText("Emisor de Archivos");
        jPanel1.add(lblTituloEmisor);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 20));

        jLabel2.setText("<html><strong>Instrucciones: </strong> <br>1. Ingresa el nombre de usuario con el que se te identificará.<br>2. Ingresa la IP de la autoridad certificadora.<br>3. Ingresa la IP del servidor a donde enviarás el archivo.<br>4. Solicita tus claves.<br>5. Elige tu archivo a enviar.<html>");
        jLabel2.setMaximumSize(new java.awt.Dimension(800, 20));
        jPanel4.add(jLabel2);

        jPanel2.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jPanel6.setLayout(new java.awt.GridLayout(1, 2));

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Solicitud de llaves"));

        jLabel3.setText("IP cliente:");

        jtfIPCliente.setEditable(false);

        jLabel6.setText("Nombre de usuario:");

        jLabel7.setText("IP de autoridad:");

        btnSolicitarClave.setText("Solicitar clave");
        btnSolicitarClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolicitarClaveActionPerformed(evt);
            }
        });

        jLabel4.setText("Clave pública:");

        jtfClavePublica.setEditable(false);

        jtfClavePrivada.setEditable(false);

        jLabel5.setText("Clave privada:");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtfClavePrivada)
                    .addComponent(jtfClavePublica)
                    .addComponent(btnSolicitarClave, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                    .addComponent(jtfIpAutoridad, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                    .addComponent(jtfNombreUsuario)
                    .addComponent(jtfIPCliente))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfIPCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtfIpAutoridad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtfNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtfClavePublica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtfClavePrivada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSolicitarClave)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel6.add(jPanel7);

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Envío del Archivo"));

        btnElegirArchivo.setText("Elegir archivo");
        btnElegirArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElegirArchivoActionPerformed(evt);
            }
        });

        jLabel8.setText("IP servidor:");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnElegirArchivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jtfIPServidor, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jtfIPServidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnElegirArchivo)
                .addContainerGap(176, Short.MAX_VALUE))
        );

        jPanel6.add(jPanel8);

        jPanel2.add(jPanel6, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnElegirArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElegirArchivoActionPerformed
        if (!clavesCorrecto) {
            JOptionPane.showMessageDialog(EmisorArchivoForm.this,
                    "Asegurate de solicitar y obtener correctamente tus claves"
                    + " pública y privada",
                    "Error", JOptionPane.ERROR_MESSAGE);
        } else if (jtfIPServidor.getText().isEmpty()) {
            JOptionPane.showMessageDialog(EmisorArchivoForm.this,
                    "Asegúrate de colocar la IP del servidor a donde enviarás "
                    + "el archivo", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            JFileChooser fileChooser = new JFileChooser();
            int returnVal = fileChooser.showOpenDialog(EmisorArchivoForm.this);
            if (returnVal == JFileChooser.APPROVE_OPTION) {
                final File file = fileChooser.getSelectedFile();
                DialogLoading dialogLoading = new DialogLoading(this, true);
                new Thread(new Runnable() {
                    @Override
                    public void run() {
                        try {
                            clienteEmisor.sendFile(file.getAbsolutePath());
                        } catch (IOException ex) {
                            JOptionPane.showMessageDialog(EmisorArchivoForm.this,
                                    "Error en el envío del archivo", "Error",
                                    JOptionPane.ERROR_MESSAGE);
                        }
                        dialogLoading.setVisible(false);
                    }
                }).start();
                dialogLoading.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(EmisorArchivoForm.this,
                        "Cancelaste el envío del archivo", "Cancelación",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnElegirArchivoActionPerformed

    private void btnSolicitarClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolicitarClaveActionPerformed
        clavesCorrecto = true;
        if (jtfIpAutoridad.getText().isEmpty()
                || jtfNombreUsuario.getText().isEmpty()) {
            clavesCorrecto = false;
        }
        if (!clavesCorrecto) {
            JOptionPane.showMessageDialog(EmisorArchivoForm.this,
                    "Asegúrate de colocar la IP de la autoridad y el nombre "
                    + "de usuario con el que deseas registrarte",
                    "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                clienteEmisor = new Cliente(jtfNombreUsuario.getText(),
                        jtfIpAutoridad.getText(), jtfIPServidor.getText());
                clienteEmisor.solicitarLLaves();
                jtfClavePrivada.setText(clienteEmisor.getPrivateKey() == null
                        ? "No asignada" : "Asignada");
                jtfClavePublica.setText(clienteEmisor.getPublicKey() == null
                        ? "No asignada" : "Asignada");
                clavesCorrecto = clienteEmisor.getPrivateKey() != null
                        && clienteEmisor.getPublicKey() != null;
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(EmisorArchivoForm.this,
                        "Error en la solicitud de llaves a la autoridad "
                        + "certificadora",
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnSolicitarClaveActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        jtfIPCliente.setText(DetectorIP.detectarIP());
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmisorArchivoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmisorArchivoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmisorArchivoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmisorArchivoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmisorArchivoForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnElegirArchivo;
    private javax.swing.JButton btnSolicitarClave;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTextField jtfClavePrivada;
    private javax.swing.JTextField jtfClavePublica;
    private javax.swing.JTextField jtfIPCliente;
    private javax.swing.JTextField jtfIPServidor;
    private javax.swing.JTextField jtfIpAutoridad;
    private javax.swing.JTextField jtfNombreUsuario;
    private javax.swing.JLabel lblTituloEmisor;
    // End of variables declaration//GEN-END:variables

    private Cliente clienteEmisor;
    private boolean clavesCorrecto;

    private void configure() {
        setLocationRelativeTo(null);
        setResizable(false);
        jtfIpAutoridad.setText(DetectorIP.detectarIP());
        jtfNombreUsuario.setText("usuario");
        jtfIPServidor.setText(DetectorIP.detectarIP());
    }
}
